### ISSUE TITLE
Limit StreamReader to use a specifed number of cores

### ISSUE THREAD

**Issue by DanTremonti** [pytorch/audio#2855] opened 2022-11-16 07:44 UTC
### Impact of number of cores on StreamReader's performance:

Unlike `torchaudio.load`, the time taken by `StreamReader` to load an audio files (`.opus` files specifically) varies a lot from machine-to-machine. The inference is that, this variation (in loading time) is related to the number of cores in the machine as well as the length of audio samples.

Given the high expense of CPU usage by StreamReader (varies with machine) against a max CPU usage of 100% by `torchaudio.load`, it is expected to perform better than the latter. But this is not always the case.

Hence, the ability to limit/set the number of CPU cores to be used by `StreamReader` is required.

### How to reproduce

[Notebook to reproduce this behaviour](https://colab.research.google.com/drive/1IH13cVRkfeUnknrLzbVgxdP7y0c2VESd?usp=sharing)
Iterate the provided function `audio_loader_sr` for the given dataset and note the time taken.

### What was tested

A dataset of `.opus` files was loaded by iterating the below functions - `audio_loader` and `audio_loader_sr`. The average duration of audio samples in the provided `valentini` dataset is ~`2.95s`. For such short audio files, distributing the loading across all available cores seems to create a dip in the performance on machines with many cores.

### Results

The following benchmarking was done in different machines with different number of cores, to load 1000 `.opus` files

num_cores | Time taken
:--------------:|:--------------:
12   |  00:15s
24   |  00:12s
256 |  01:11s

### Some other benchmarking references
- [Ref1](https://streaminglearningcenter.com/blogs/ffmpeg-command-threads-how-it-affects-quality-and-performance.html)
- [Ref2](https://superuser.com/a/1196163/1747713)

### Solution

The underlying ffmpeg library has an option to set the number of cores to be used to load the audio, using `-threads` arg. The auto detection of the `-threads` value may not be preferable for all scenarios (say, we want to obtain a constant loading time in a certain machine at different times) and also does not always seem to do a good job in terms of loading times. If we could pass this argument value using `StreamReader`, we would be able to limit the number of cores used.

**Comment by mthrok** [comment] 2022-11-16 17:46
Hi

Thanks for the detailed report. Could you try passing `decoder_option={"threads": "NUM_THREADS"}` to `add_XXX_stream` and see if that makes difference?

Looking at the source code of the ffmepg CLI ([`ffmpeg`](https://github.com/FFmpeg/FFmpeg/blob/822da7a31746b8a5ec92c854b52bc767e6e98e8a/fftools/ffmpeg.c#L2579-L2593), [`ffplay`](https://github.com/FFmpeg/FFmpeg/blob/822da7a31746b8a5ec92c854b52bc767e6e98e8a/fftools/ffplay.c#L2616-L2620)), it seems that `threads` are set par stream, and `decoder_option` is somewhat analogous in `StreamReader`.

**Comment by DanTremonti** [comment] 2022-11-17 05:11
Thank you for the suggestion. I tried
```
streamreader_obj.add_basic_audio_stream(
    frames_per_chunk=sampling_rate,
    decoder_option={"threads": str(num_threads)},
)
```
But the CPU usage is constant (~600%) for num_threads: 1,2,4,8 in a machine with 12 cores. The time taken to load the files also did not change.

**Comment by mthrok** [comment] 2022-11-28 05:47
> Thank you for the suggestion. I tried
> 
> ```
> streamreader_obj.add_basic_audio_stream(
>     frames_per_chunk=sampling_rate,
>     decoder_option={"threads": str(num_threads)},
> )
> ```
> 
> But the CPU usage is constant for varying `num_threads`: CPU usage = ~600% for num_threads: 1,2,4,8 in a machine with 12 cores. CPU usage = ~540% for num_threads: 1,2,4,8,16 in a machine with 24 cores.
> 
> The time taken to load the files also did not change.

@DanTremonti Could you show equivalent ffmpeg commands to test the threading for your OPUS decoding case? I remember reading about ffmpeg threading behavior being inconsistent across decoders. The reference 1 and almost all ffmpeg performance talks are about video processing. It's easier for me to find the right nob if there is a reference ffmpeg command.

**Comment by DanTremonti** [comment] 2022-12-02 10:58
> @DanTremonti Could you show equivalent ffmpeg commands to test the threading for your OPUS decoding case? I remember reading about ffmpeg threading behavior being inconsistent across decoders. The reference 1 and almost all ffmpeg performance talks are about video processing. It's easier for me to find the right nob if there is a reference ffmpeg command.

@mthrok I ran the below python script in a 256 core machine.
```
import subprocess
from tqdm import tqdm

it = 1000
threads = [1, 2, 4, 8, 16, 32, 64, 128, 256]
opus_path = "<path-to-opus-file>"

def load_audio_ffmpeg(audio_path, threads=None):

    # init command
    if threads:
        ffmpeg_command = [
            "ffmpeg",
            "-threads", str(threads),
            "-i", audio_path,
            "-threads", str(threads),
            "-acodec", "libopus", "-f", "wav", "pipe:1",
        ]
    else:
        ffmpeg_command = [
            "ffmpeg",
            "-i", audio_path,
            "-acodec", "libopus", "-f", "wav", "pipe:1",
        ]

    # excute ffmpeg command
    pipe = subprocess.run(ffmpeg_command,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        bufsize=10**8,
    )

    # debug
    # print(pipe.stdout, pipe.stderr)


for thread in threads:
    for _ in tqdm(range(it), desc=str(thread)):
        load_audio_ffmpeg(opus_path, thread)

for _ in tqdm(range(it), desc="unspecified"):
    load_audio_ffmpeg(opus_path)
```

And this was the output:

![image](https://user-images.githubusercontent.com/58321625/205277635-9432ed7e-dc78-433a-9517-a6626f4a0c57.png)

**Comment by DanTremonti** [comment] 2022-12-02 11:14
With regard to
> Could you try passing decoder_option={"threads": "NUM_THREADS"} to add_XXX_stream and see if that makes difference?

I came across [this](https://github.com/cisco/openh264/issues/1889#issuecomment-91018851) thread. This made me wonder at which position relative to `-i` option does the passed `decoder_option` get placed.

**Comment by mthrok** [comment] 2022-12-05 23:43
@DanTremonti What's the version of your ffmpeg? 

The command you used does not work with my ffmpeg 4.2.2. 

`-i <audio_path> -acodec libopus -f wav pipe:1`  generates the following error.

```
[libopus @ 0x55e59073aec0] No bit rate set. Defaulting to 64000 bps.
[wav @ 0x55e590739780] opus codec not supported in WAVE format
Could not write header for output file #0 (incorrect codec parameters ?): Function not implemented
Error initializing output stream 0:0 --
Conversion failed!
```

<img width="713" alt="Screen Shot 2022-12-05 at 6 20 03 PM" src="https://user-images.githubusercontent.com/855818/205764407-148227f6-24e0-419c-9bcd-2a92f53d7568.png">

In my understanding, options provided after `-i <input>` are for output file, so the above command suggests that decode the input file, then encode it with libopus and write as WAV format, thus leading to the error.

---

Looking at the decoder help message libopus does not support threading.

```
$ ffmpeg -h decoder=libopus

Decoder libopus [libopus Opus]:
    General capabilities: dr1
    Threading capabilities: none
                            ^^^^
    Supported sample formats: flt s16
libopusdec AVOptions:
  -apply_phase_inv   <boolean>    .D..A.... Apply intensity stereo phase inversion (default true)
```

I tried changing the thread option, but no change in runtime.

<details><summary>script</summary>

```bash
#!/usr/bin/env bash

filename="test.opus"

if [ ! -e "${filename}" ]; then
    ffmpeg -f lavfi -i "sine=sample_rate=48000:frequency=360:duration=600" "${filename}"
fi

echo -e "thread: $(nproc)"
time ffmpeg -hide_banner -acodec libopus -i "${filename}" -f wav pipe:2 2> /dev/null;

for thread in 1 8 16 32 64 96; do
    echo -e "thread: ${thread}"
    numactl --physcpubind=0-"$(( thread - 1 ))" nproc
    time numactl --physcpubind=0-"$(( thread - 1 ))" ffmpeg -hide_banner -threads "${thread}" -i "${\
filename}"  -f wav pipe:2 2> /dev/null;
    echo -e "\n"
done

```
</details>

<details><summary>result</summary>

```
thread: 96

real	0m1.341s
user	0m1.297s
sys	0m0.028s
thread: 1
1

real	0m1.183s
user	0m1.143s
sys	0m0.020s


thread: 8
8

real	0m1.185s
user	0m1.141s
sys	0m0.028s


thread: 16
16

real	0m1.181s
user	0m1.144s
sys	0m0.024s


thread: 32
32

real	0m1.190s
user	0m1.146s
sys	0m0.032s


thread: 64
64

real	0m1.183s
user	0m1.150s
sys	0m0.025s


thread: 96
96

real	0m1.177s
user	0m1.143s
sys	0m0.024s
```

</details>


---

Coming back to the original issue, I changed the number of CPU cores and see how it affects the decoding, and I do not observe the issue.

<details><summary>script</summary>

```bash

#!/usr/bin/env bash

filename="test.opus"

if [ ! -e "${filename}" ]; then
    ffmpeg -f lavfi -i "sine=sample_rate=48000:frequency=360:duration=600" "${filename}"
fi

for thread in 1 8 16 32 64 96; do
    echo -e "thread: ${thread}"
    numactl --physcpubind=0-"$(( thread - 1 ))" nproc
    numactl --physcpubind=0-"$(( thread - 1 ))" \
            python -m timeit -n 1 -r 5 -s \
            "from torchaudio.io._compat import load_audio" "load_audio(\"${filename}\")"
    echo -e "\n"
done
```

</details>

<details><summary>result</summary>

```
thread: 1
1
1 loop, best of 5: 1.27 sec per loop


thread: 8
8
1 loop, best of 5: 1.3 sec per loop


thread: 16
16
1 loop, best of 5: 1.3 sec per loop


thread: 32
32
1 loop, best of 5: 1.34 sec per loop


thread: 64
64
1 loop, best of 5: 1.3 sec per loop


thread: 96
96
1 loop, best of 5: 1.33 sec per loop
```

</details>

**Comment by DanTremonti** [comment] 2022-12-06 06:30
>@DanTremonti What's the version of your ffmpeg?

ffmpeg version 4.2.7-0ubuntu0.1

---
>In my understanding, options provided after -i <input> are for output file ...

@mthrok Yes you are right. The code snippet I shared was setting `-threads` to encode the audio too. So, I modified the command and executed the script again.
<details>
<summary>modified code block</summary>
<br>

```py
    # init command
    if threads:
        ffmpeg_command = [
            "ffmpeg",
            "-threads", str(threads),
            "-i", audio_path,
            "-f", "libopus", "pipe:1",
        ]
    else:
        ffmpeg_command = [
            "ffmpeg",
            "-i", audio_path,
            "-f", "libopus", "pipe:1",
        ]
```
</details>

Here is the output:
![image](https://user-images.githubusercontent.com/58321625/205834650-96b4c548-b84a-4fff-a24c-17986907391e.png)

The above output should again confirm your comment:
>Looking at the decoder help message libopus does not support threading.

Summarising,
- `StreamReader`
  - the latency of loading a `.opus` file using `StreamReader` varies with the number of cores in the machine.
  - passing `-threads` through `StreamReader`'s `decoder_option` argument didn't work for loading `.opus` files.
  - loading `.opus` file seems to consume >100% cpu in machines with multiple cores.
- `ffmpeg`
  - `libopus` and `opus` decoders do not support threading
  - loading `.opus` file using the above code snippet seems to consume <=100% cpu in machines with multiple cores.

Although, I'm guessing `StreamReader` uses a default decoder to load a `.opus` file, would figuring out which one it is help?

**Comment by DanTremonti** [comment] 2022-12-12 13:41
@mthrok I ran the [mentioned script](https://github.com/pytorch/audio/issues/2855#:~:text=observe%20the%20issue.-,script,-result).

Here are the results:

<details>
<summary>Run 1: `threads - 1 2 4 8 16 32 64 128 256`</summary>
<br>

![image](https://user-images.githubusercontent.com/58321625/207056432-1fb27e29-6b0e-4922-8646-d8111c9a55a7.png)
</details>

<details>
<summary>Run 2: `threads - 1 2 4 8 16 32 64 128 256`</summary>
<br>

![image](https://user-images.githubusercontent.com/58321625/207056512-725cdd83-138f-437b-be9a-2e66fd3da79e.png)
</details>

<details>
<summary>Run 3: `threads - 1 2 4 8 16 32 64 128 192`</summary>
<br>

![image](https://user-images.githubusercontent.com/58321625/207057891-7c3a722b-9246-4b3b-b44f-613b37b2b046.png)
</details>

I also noticed that the CPU usage scaled from 1 to 128 thread values, ranging from:
- thread=1 -> CPU usage=100%
- thread=64 -> CPU usage=~6200%
- thread=128 -> CPU usage=~12200%

Without passing `decoder_option`, the CPU usage was 100% (same as when `thread=1`) and the output:
![image](https://user-images.githubusercontent.com/58321625/207058820-a2fe1043-3e8d-4abd-bdfd-df7e6875e19c.png)

**Comment by mthrok** [comment] 2022-12-25 22:01
@DanTremonti The result looks like it is fine for CPU count < 64. It does not look like StreamReader is using all the CPUs, instead there is something strange going on when CPU count is >=64. Perhaps it's something else with your system.

I will close the issue because I cannot reproduce the issue, and it's highly unlike that your issue is caused by StreamReader.

**Comment by mthrok** [comment] 2023-01-02 22:13
Re-opening this issue as I encounter some issue when modifying the number of available CPU cores.

Looking at torchvision's codebase, looks like `thread_count` and `thread_type` need to be set.

https://github.com/pytorch/vision/blob/32d254bbfcf14975f846765775584e61ef25a5bc/torchvision/csrc/io/decoder/stream.cpp#L60-L75

(although, at a glance, the way the `thread_type` is set seems not correct there.)
The capacity constants related threading seem to be the following three

- [AV_CODEC_CAP_FRAME_THREADS](https://ffmpeg.org/doxygen/4.2/group__lavc__core.html#gae21e6310b40920cd61f54e9c320d8e6c) - [FF_THREAD_FRAME](https://ffmpeg.org/doxygen/4.2/avcodec_8h.html#a116c7fb56ac57ccca3e08b80467b2a40)
- [AV_CODEC_CAP_SLICE_THREADS](https://ffmpeg.org/doxygen/4.2/group__lavc__core.html#ga7c4f386d1d6df0214eb35f2be1c82779) - [FF_THREAD_SLICE](https://ffmpeg.org/doxygen/4.2/avcodec_8h.html#a91bc1a1c1c4a3cc6db54d59705fded0b)
- [AV_CODEC_CAP_AUTO_THREADS](https://ffmpeg.org/doxygen/4.2/group__lavc__core.html#gaec1cd58fda7b88067a3402cddc9b4b96)

**Comment by mthrok** [comment] 2023-01-02 22:36
well actually, looking at the example, it seems possible to set `thread_type` via dictionary.

https://github.com/FFmpeg/FFmpeg/blob/cc2b1a325162fd76969ce21fff9ba84228bc8212/tools/venc_data_dump.c#L85-L99

**Comment by mthrok** [comment] 2023-01-04 18:52
Note: 

In https://github.com/pytorch/audio/pull/2949, we are setting the default number of decoder threads to 1.

I was not able to reproduce the issue described here, and the only hypothesis I have at the moment for 
the reported phenomenon is that  the fact that we did not set default thread number is causing some issue.

(FFmpeg CLIs sets to value `"auto"` by default)

It is my best belief that #2949 resolves the issue.

**Closed** 2023-01-04 22:13 UTC
Labels: triaged

**Comment by DanTremonti** [comment] 2023-01-05 04:51
@mthrok thanks!
