### ISSUE TITLE
Reverb effect - Error in `python': corrupted double-linked list

### ISSUE THREAD

**Issue by brianc118** [pytorch/audio#467] opened 2020-03-20 10:01 UTC
## 🐛 Bug

Getting "Error in `python': corrupted double-linked list" error. 

> Error in `python': corrupted double-linked list: 0x000055d6aeea0e10 ***

I can't find example usages of the reverb effect elsewhere but this I believe this is the right usage (otherwise SoX should throw an error).

## To Reproduce

```
E = torchaudio.sox_effects.SoxEffectsChain()
E.set_input_file(filename)
E.append_effect_to_chain("reverb", [50.0])
x, sr = E.sox_build_flow_effects()
```

Backtrace: https://gist.github.com/brianc118/05519d0242286fdddfbebe28c722bd06

## Environment

```
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: CentOS Linux release 7.7.1908 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
CMake version: version 3.15.3

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.168
GPU models and configuration: GPU 0: Tesla K40m
Nvidia driver version: 418.67
cuDNN version: Probably one of the following:
/opt/local/stow/cudnn-10.0-v7.5.1.10/lib64/libcudnn.so.7.5.1
/opt/local/stow/cudnn-7.0-linux-x64-v3.0-prod/lib64/libcudnn.so.7.0.64
/opt/local/stow/cudnn-7.0-linux-x64-v4.0-prod/lib64/libcudnn.so.4.0.7
/opt/local/stow/cudnn-8.0-linux-x64-v5.1/lib64/libcudnn.so.5.1.10
/opt/local/stow/cudnn-8.0-linux-x64-v6.0/lib64/libcudnn.so.6.0.21
/opt/local/stow/cudnn-9.0-linux-x64-v7/lib64/libcudnn.so.7.1.4
/usr/lib64/libcudnn.so.7.5.1

Versions of relevant libraries:
[pip3] numpy==1.10.4
[conda] torch                     1.4.0                    pypi_0    pypi
[conda] torchaudio                0.4.0                    pypi_0    pypi
```

**Comment by vincentqb** [comment] 2020-03-24 18:11
I can't reproduce the same error, but I do get a segmentation fault and/or an error.

```python
In [1]: filename = "sinewave.wav"
In [2]: import torchaudio
In [3]: E = torchaudio.sox_effects.SoxEffectsChain()
In [4]: E.set_input_file(filename)
In [5]: E.append_effect_to_chain("reverb", [50.0])
In [6]: x, sr = E.sox_build_flow_effects()

zsh: segmentation fault (core dumped)
```

```python
In [1]: filename = "sinewave.wav"
In [2]: import torchaudio
In [3]: E = torchaudio.sox_effects.SoxEffectsChain()
In [4]: E.append_effect_to_chain("reverb", 50.0)
In [5]: x, sr = E.sox_build_flow_effects()

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-437cda69b739> in <module>
----> 1 x, sr = E.sox_build_flow_effects()

~/anaconda3/envs/audio-built/lib/python3.7/site-packages/torchaudio-0.5.0a0+542fbdf-py3.7-linux-x86_64.egg/torchaudio/_backend.py in wrapper(*args, **kwargs)
     50             if get_audio_backend() not in backends:
     51                 raise RuntimeError("Function {} requires backend to be one of {}.".format(func.__name__, backends))
---> 52             return func(*args, **kwargs)
     53         return wrapper
     54 

~/anaconda3/envs/audio-built/lib/python3.7/site-packages/torchaudio-0.5.0a0+542fbdf-py3.7-linux-x86_64.egg/torchaudio/sox_effects.py in sox_build_flow_effects(self, out)
    150                                            self.filetype,
    151                                            self.chain,
--> 152                                            self.MAX_EFFECT_OPTS)
    153 
    154         torchaudio._audio_normalization(out, self.normalization)

TypeError: build_flow_effects(): incompatible function arguments. The following argument types are supported:
    1. (arg0: str, arg1: at::Tensor, arg2: bool, arg3: _torch_sox.sox_signalinfo_t, arg4: _torch_sox.sox_encodinginfo_t, arg5: str, arg6: List[_torch_sox.SoxEffect], arg7: int) -> int

Invoked with: None, tensor([]), True, None, None, 'raw', [SoxEffect (reverb ,["50.0"])
], 20
```

**Comment by vincentqb** [comment] 2020-03-24 18:15
Do you have the corresponding command in sox that works?

**Comment by tomassosorio** [comment] 2020-03-24 22:18
I just tried running your code @vincentqb and it did not occur any error to me.

Using:
macos: Mojave 10.14.6
sox: 14.4.2_3
torchaudio:  0.4.0

**Comment by tomassosorio** [comment] 2020-03-24 22:29
Trying to replicate the error running the snipped from @vincentqb, it produced the effect correctly.

Using:
macos: Mojave 10.14.6
torchaudio: 0.4.0
sox: 14.4.2_3

**Comment by brianc118** [comment] 2020-03-26 04:42
@vincentqb I'm not sure what your second snippet is trying to do since you don't call `set_input_file()`.

I can reproduce the same segfault with `sinewave.wav`. However it seems to be dependent on wav file. For example, if the file is steam-train-whistle-daniel_simon.wav then there is no segfault.

```
import faulthandler

faulthandler.enable()

filename = "steam-train-whistle-daniel_simon.wav"

import torchaudio
E = torchaudio.sox_effects.SoxEffectsChain()
E.set_input_file(filename)
E.append_effect_to_chain("reverb", [50.0])
x, sr = E.sox_build_flow_effects()
torchaudio.save('out.wav', x, sr)
```

Runs fine. However if we set it to sinewave.wav we get the following segfault

```
Fatal Python error: Segmentation fault

Current thread 0x00007fe7d8d1a740 (most recent call first):
  File "/home/Student/s4396976/miniconda2/envs/pytorch/lib/python3.7/site-packages/torchaudio/sox_effects.py", line 152 in sox_build_flow_effects
  File "/home/Student/s4396976/miniconda2/envs/pytorch/lib/python3.7/site-packages/torchaudio/_backend.py", line 51 in wrapper
  File "test.py", line 11 in <module>
[1]    42171 segmentation fault  python test.py
```

**Comment by brianc118** [comment] 2020-03-26 04:52
> Do you have the corresponding command in sox that works?

`sox sinewave.wav out.wav reverb 50`

**Comment by vincentqb** [comment] 2020-03-30 22:00
Thanks for pointing out the typo, I corrected the example above :)

**Comment by vincentqb** [comment] 2020-03-30 22:03
Do you know if there's a previous version of torchaudio for which it ever worked?

**Comment by tomassosorio** [comment] 2020-03-31 08:41
It works with macos, I tried in the other day with the snipped that you provided @vincentqb

**Comment by brianc118** [comment] 2020-04-15 00:54
> Do you know if there's a previous version of torchaudio for which it ever worked?

I'm not aware of any version that worked. I've only started using torchaudio recently.

**Comment by cpuhrsch** [comment] 2020-04-29 02:24
@brianc118 - I was able to reproduce this with an earlier install of torchaudio on Mac, but your snippet succeeded after I updated to our most recent version. Here is the exact code I executed

```
import torch
import torchaudio
filename = "./test/assets/sinewave.wav"
E = torchaudio.sox_effects.SoxEffectsChain()
E.set_input_file(filename)
E.append_effect_to_chain("reverb", [50.0])
x, sr = E.sox_build_flow_effects()
```

Please let me know if this is still an issue after the update.

**Comment by brianc118** [comment] 2020-04-30 02:00
@cpuhrsch I'm still getting this on linux (CentOS) after updating to version 0.5.0, running the exact code you listed.

**Comment by mthrok** [comment] 2020-11-03 21:00
closing the issue as `SoxEffectsChain` has been removed from torchaudio in #977.

**Closed by mthrok** 2020-11-03 21:00 UTC
