### ISSUE TITLE
Multiprocessing error in Device ASR tutorial

### ISSUE THREAD

**Issue by forresti** [pytorch/audio#2793] opened 2022-10-24 23:19 UTC
### 🐛 Describe the bug

I've tried running several of the torchaudio tutorials, and they work for me. But, I am hitting an error in this tutorial: https://pytorch.org/audio/0.12.0/tutorials/device_asr.html

The error is:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/fni/opt/anaconda3/envs/oct2022/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/fni/opt/anaconda3/envs/oct2022/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'stream' on <module '__main__' (built-in)>
```

The code (copy/pasted from the tutorial) is:

```python
import torch
import torchaudio
from torchaudio.io import StreamReader

NUM_ITER = 100


def stream(q, format, src, segment_length, sample_rate):
    from torchaudio.io import StreamReader

    print("Building StreamReader...")
    streamer = StreamReader(src, format=format)
    streamer.add_basic_audio_stream(frames_per_chunk=segment_length, sample_rate=sample_rate)

    print(streamer.get_src_stream_info(0))
    print(streamer.get_out_stream_info(0))

    print("Streaming...")
    print()
    stream_iterator = streamer.stream(timeout=-1, backoff=1.0)
    for _ in range(NUM_ITER):
        (chunk,) = next(stream_iterator)
        q.put(chunk)

class Pipeline:
    """Build inference pipeline from RNNTBundle.

    Args:
        bundle (torchaudio.pipelines.RNNTBundle): Bundle object
        beam_width (int): Beam size of beam search decoder.
    """

    def __init__(self, bundle: torchaudio.pipelines.RNNTBundle, beam_width: int = 10):
        self.bundle = bundle
        self.feature_extractor = bundle.get_streaming_feature_extractor()
        self.decoder = bundle.get_decoder()
        self.token_processor = bundle.get_token_processor()

        self.beam_width = beam_width

        self.state = None
        self.hypothesis = None

    def infer(self, segment: torch.Tensor) -> str:
        """Perform streaming inference"""
        features, length = self.feature_extractor(segment)
        hypos, self.state = self.decoder.infer(
            features, length, self.beam_width, state=self.state, hypothesis=self.hypothesis
        )
        self.hypothesis = hypos[0]
        transcript = self.token_processor(self.hypothesis[0], lstrip=False)
        return transcript

class ContextCacher:
    """Cache the end of input data and prepend the next input data with it.

    Args:
        segment_length (int): The size of main segment.
            If the incoming segment is shorter, then the segment is padded.
        context_length (int): The size of the context, cached and appended.
    """

    def __init__(self, segment_length: int, context_length: int):
        self.segment_length = segment_length
        self.context_length = context_length
        self.context = torch.zeros([context_length])

    def __call__(self, chunk: torch.Tensor):
        if chunk.size(0) < self.segment_length:
            chunk = torch.nn.functional.pad(chunk, (0, self.segment_length - chunk.size(0)))
        chunk_with_context = torch.cat((self.context, chunk))
        self.context = chunk[-self.context_length :]
        return chunk_with_context

def main(device, src, bundle):
    print(torch.__version__)
    print(torchaudio.__version__)

    print("Building pipeline...")
    pipeline = Pipeline(bundle)

    sample_rate = bundle.sample_rate
    segment_length = bundle.segment_length * bundle.hop_length
    context_length = bundle.right_context_length * bundle.hop_length

    print(f"Sample rate: {sample_rate}")
    print(f"Main segment: {segment_length} frames ({segment_length / sample_rate} seconds)")
    print(f"Right context: {context_length} frames ({context_length / sample_rate} seconds)")

    cacher = ContextCacher(segment_length, context_length)

    @torch.inference_mode()
    def infer():
        print("in infer()")
        for _ in range(NUM_ITER):
            print("infer() iter")
            chunk = q.get()
            segment = cacher(chunk[:, 0])
            transcript = pipeline.infer(segment)
            print(transcript, end="", flush=True)

    import torch.multiprocessing as mp

    ctx = mp.get_context("spawn")
    q = ctx.Queue()
    p = ctx.Process(target=stream, args=(q, device, src, segment_length, sample_rate))
    p.start()
    infer()
    p.join()


if __name__ == "__main__":
    main(
        device="avfoundation",
        src=":1",
        bundle=torchaudio.pipelines.EMFORMER_RNNT_BASE_LIBRISPEECH,
    )
```

### Versions

```
$ python ./collect_env.py
Collecting environment information...
PyTorch version: 1.14.0.dev20221022
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.6 (x86_64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.102)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.13 (main, Oct 13 2022, 16:12:30)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.3
[pip3] torch==1.14.0.dev20221022
[pip3] torchaudio==0.14.0.dev20221024
[pip3] torchvision==0.15.0.dev20221024
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.4.0           hecd8cb5_637
[conda] mkl-service               2.4.0            py39h9ed2024_0
[conda] mkl_fft                   1.3.1            py39h4ab4a9b_0
[conda] mkl_random                1.2.2            py39hb2f4e1b_0
[conda] numpy                     1.23.3           py39hce7a837_0
[conda] numpy-base                1.23.3           py39heddfccc_0
[conda] pytorch                   1.14.0.dev20221022         py3.9_0    pytorch-nightly
[conda] torchaudio                0.14.0.dev20221024        py39_cpu    pytorch-nightly
[conda] torchvision               0.15.0.dev20221024        py39_cpu    pytorch-nightly
```

**Comment by mthrok** [comment] 2022-10-25 00:33
Hi @forresti 

Thanks for trying the tutorials. Glad to hear that they work fine for you.

Regarding the error you encounter, it is coming from Python's `multiprocessing` module. `multiprocessing` module passes target functions to the subprocesses by pickling and un-pickling them.

The `AttributeError` means that it could not find the object called `stream` in `__main__` scope.
However, this is puzzling to me. I tried the code on my laptop (macOS, Python 3.9) just now and it works fine.


https://user-images.githubusercontent.com/855818/197655262-997bc142-71e8-4be5-a111-529c29e104bd.mov

Often issues with `multiprocessing` is related to start method and typically [changing the start method](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods) makes it work, though it comes with complicated cost/disadvantage, but I think it's fine for the sake of running the tutorial.

(Note that Python for macOS changed its default to `spawn` in Python 3.8, but I don't think that's relevant here.)

**Comment by forresti** [comment] 2022-10-26 18:22
Thanks a lot for looking into this, @mthrok!

Here's an other clue... When I prints the "AttributeError" thing, the code doesn't exit, but I think the code does eventually hang.

When I hit the "stop" button in Jupyter (basically Ctrl+C), it always seems to stop at the following place in the code:

```
KeyboardInterrupt

Traceback (most recent call last)
Input In [10], in <cell line: 40>()
     37     p.join()
     40 if __name__ == "__main__":
---> 41     main(
     42         device="avfoundation",
     43         src=":1",
     44         bundle=torchaudio.pipelines.EMFORMER_RNNT_BASE_LIBRISPEECH,
     45     )

Input In [10], in main(device, src, bundle)
     34 p = ctx.Process(target=stream, args=(q, device, src, segment_length, sample_rate))
     35 p.start()
---> 36 infer()
     37 p.join()

File ~/opt/anaconda3/envs/oct2022/lib/python3.9/site-packages/torch/autograd/grad_mode.py:27, in _DecoratorContextManager.__call__.<locals>.decorate_context(*args, **kwargs)
     24 @functools.wraps(func)
     25 def decorate_context(*args, **kwargs):
     26     with self.clone():
---> 27         return func(*args, **kwargs)

Input In [10], in main.<locals>.infer()
     18 @torch.inference_mode()
     19 def infer():
     20     for _ in range(NUM_ITER):         
---> 21         chunk = q.get()
     22         print("q.get()")
     24         segment = cacher(chunk[:, 0])

File ~/opt/anaconda3/envs/oct2022/lib/python3.9/multiprocessing/queues.py:103, in Queue.get(self, block, timeout)
    101 if block and timeout is None:
    102     with self._rlock:
--> 103         res = self._recv_bytes()
    104     self._sem.release()
    105 else:

File ~/opt/anaconda3/envs/oct2022/lib/python3.9/multiprocessing/connection.py:221, in _ConnectionBase.recv_bytes(self, maxlength)
    219 if maxlength is not None and maxlength < 0:
    220     raise ValueError("negative maxlength")
--> 221 buf = self._recv_bytes(maxlength)
    222 if buf is None:
    223     self._bad_message_length()

File ~/opt/anaconda3/envs/oct2022/lib/python3.9/multiprocessing/connection.py:419, in Connection._recv_bytes(self, maxsize)
    418 def _recv_bytes(self, maxsize=None):
--> 419     buf = self._recv(4)
    420     size, = struct.unpack("!i", buf.getvalue())
    421     if size == -1:

File ~/opt/anaconda3/envs/oct2022/lib/python3.9/multiprocessing/connection.py:384, in Connection._recv(self, size, read)
    382 remaining = size
    383 while remaining > 0:
--> 384     chunk = read(handle, remaining)
    385     n = len(chunk)
    386     if n == 0:

```

**Comment by mthrok** [comment] 2022-11-02 23:05
The error is happening at multiprocessing queue. 
The error suggests it's more about environment rather than torchaudio.
Can you remove all the torchaudio code and see what happens?

Also perhaps can you try outside of Jupyter notebook?

**Comment by mthrok** [comment] 2023-07-31 18:32
FYI: `multiprocessing` does not work with IPython.

https://stackoverflow.com/questions/41385708/multiprocessing-example-giving-attributeerror/65001152#65001152

So there is a good chance that this is the cause.
I close the issue.

**Closed by mthrok** 2023-07-31 18:32 UTC
