### ISSUE TITLE
Best way to calculate the MelSpectrogram on mini-batches

### ISSUE THREAD

**Issue by vgoklani** [pytorch/audio#300] opened 2019-09-26 20:08 UTC
From the documentation, it looks like the MelSpectrogram only operates on one waveform at a time. How do we run this on a mini-batch of data?  Thank you!

**Comment by vincentqb** [comment] 2019-10-04 14:53
Currently, batch can be down through loops. For reference: #147.

**Comment by vincentqb** [comment] 2019-10-25 18:26
Closing, since this is a duplicate of #147.

**Closed by vincentqb** 2019-10-25 18:26 UTC
