### ISSUE TITLE
Support for Raspberry pi?

### ISSUE THREAD

**Issue by LearnedVector** [pytorch/audio#631] opened 2020-05-12 18:15 UTC
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

Hello, is support for raspberry pi planned?

**Comment by vincentqb** [comment] 2020-05-12 21:21
Since linux is supported on raspberry pi, have you tried compiling from source or installing using pip?

**Comment by LearnedVector** [comment] 2020-05-12 21:26
hello @vincentqb, yes i tried installing from source but running into this error `RuntimeError: fft: ATen not compiled with MKL support` when using using `torchaudio.transforms.MFCC`. Seems to be an MKL issue? Since the pi does not have an intel processor, is there anyway around this?

here is the entire stacktrace for reference

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "engine.py", line 89, in inference_loop
    action(self.predict(self.audio_q))
  File "engine.py", line 71, in predict
    mfcc = self.featurizer(waveform).transpose(1, 2).transpose(0, 1)
  File "/home/pi/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 562, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/torchaudio-0.6.0a0+00d3820-py3.7-linux-armv7l.egg/torchaudio/transforms.py", line 490, in forward
    mel_specgram = self.MelSpectrogram(waveform)
  File "/home/pi/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 562, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/torchaudio-0.6.0a0+00d3820-py3.7-linux-armv7l.egg/torchaudio/transforms.py", line 422, in forward
    specgram = self.spectrogram(waveform)
  File "/home/pi/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 562, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/torchaudio-0.6.0a0+00d3820-py3.7-linux-armv7l.egg/torchaudio/transforms.py", line 84, in forward
    self.win_length, self.power, self.normalized)
  File "/home/pi/.local/lib/python3.7/site-packages/torchaudio-0.6.0a0+00d3820-py3.7-linux-armv7l.egg/torchaudio/functional.py", line 249, in spectrogram
    waveform, n_fft, hop_length, win_length, window, True, "reflect", False, True
  File "/home/pi/.local/lib/python3.7/site-packages/torch/functional.py", line 439, in stft
    return _VF.stft(input, n_fft, hop_length, win_length, window, normalized, onesided)
RuntimeError: fft: ATen not compiled with MKL support
```

**Comment by vincentqb** [comment] 2020-05-12 21:40
I see, so pytorch doesn't support it. This means torchaudio can't either. I'll close this since this is a duplicate of #408.

**Closed by vincentqb** 2020-05-12 21:40 UTC
