### ISSUE TITLE
Inconsistent length between info() and load() for MP3 files

### ISSUE THREAD

**Issue by SamG97** [pytorch/audio#329] opened 2019-11-05 10:44 UTC
## 🐛 Bug

For single channel MP3 files, the length returned when calling torchaudio.info() is slightly longer than torchaudio.load(). For files with a sample rate of 16KHz the length provided by info is always 576 longer and for a sample rate of 48KHz the length is 1152 longer. 

## To Reproduce

```python
import torchaudio
path = ... # some MP3 file location
print(torchaudio.info(path)[0].channels)  # Verify that file is single channel
print(torchaudio.info(path)[0].length)
print(torchaudio.load(path)[0].size(1))
```

## Expected behavior

The above code should output identical lengths, e.g.
```
1
96768
96768
```

## Environment

 - What commands did you used to install torchaudio (conda/pip/build from source)?
Installed with pip using `conda env create -f environment.yml` where `environment.yml` contains the dependencies for the project

 - What does `torchaudio.__version__` print? (If applicable)
`0.3.0`

```
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1050 Ti
Nvidia driver version: 430.50
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.2.0
[pip] torchaudio==0.3.0
[pip] torchvision==0.4.0a0+6b959ee
[conda] _pytorch_select           0.1                       cpu_0    anaconda
[conda] blas                      1.0                         mkl    conda-forge/label/cf201901
[conda] mkl                       2019.4                      243    anaconda
[conda] mkl-service               2.3.0            py37he904b0f_0    anaconda
[conda] mkl_fft                   1.0.12           py37ha843d7b_0    anaconda
[conda] mkl_random                1.0.2            py37hd81dba3_0    anaconda
[conda] pytorch                   1.2.0           py3.7_cuda10.0.130_cudnn7.6.2_0    pytorch
[conda] torchaudio                0.3.0                    pypi_0    pypi
[conda] torchvision               0.4.0                py37_cu100    pytorch
```

## Additional context

Checking the length of the files with `soxi -D filename`, the length reported by info appears to be the correct one. The example code above behaves as expected (i.e. info and load agree on lengths) when using a FLAC file in my environment.

The MP3 files tested came from the [Common Voice](https://voice.mozilla.org/en) data set and converting some of the FLAC files in the [LibriSpeech](http://www.openslr.org/12) data set to MP3s.

**Comment by vincentqb** [comment] 2019-11-06 17:51
Thanks for reporting. Can you provide an example file and a minimal code? I cannot reproduce.

With [this file](https://github.com/pytorch/audio/blob/master/test/assets/whitenoise_1min.mp3):
```
>>> import torchaudio
>>> path = "whitenoise_1min.mp3"
>>> print(torchaudio.info(path)[0].channels)  # Verify that file is single channel
1
>>> print(torchaudio.info(path)[0].length)
2647279
>>> print(torchaudio.load(path)[0].size(1))
2647279
```

With [this file](https://github.com/pytorch/audio/blob/master/test/assets/commonvoice/clips/common_voice_tt_00000000.mp3) from CommonVoice:
```
>>> import torchaudio
>>> path = "common_voice_tt_00000000.mp3"
>>> print(torchaudio.info(path)[0].channels)  # Verify that file is single channel
1
>>> print(torchaudio.info(path)[0].length)
222308
>>> print(torchaudio.load(path)[0].size(1))
222308
```

**Comment by SamG97** [comment] 2019-11-07 10:34
That file behaves correctly for me but every file in the train set from the EN version of Common Voice doesn't work. Here's an example to avoid having to download the entire ~30GB dataset.
[common_voice_en_100000.zip](https://github.com/pytorch/audio/files/3819087/common_voice_en_100000.zip)

For this file, running the same script as before gives:
```
1
93312
92160
```

**Comment by vincentqb** [comment] 2019-11-07 16:17
I can reproduce with this file.

```
>>> import torchaudio
>>> path = "common_voice_en_100000.mp3"
>>> print(torchaudio.info(path)[0].channels) 
1
>>> print(torchaudio.info(path)[0].length)
93312
>>> print(torchaudio.load(path)[0].size(1))
92160
```

**Comment by vincentqb** [comment] 2019-11-07 17:02
The backend of torchaudio uses sox's load and info libraries. The discrepancy is coming from there.

The number of samples reported by sox is the same as that of the waveform.
```
❯ sox  common_voice_en_100000.mp3 -n stat

Samples read:             92160
Length (seconds):      1.920000
Scaled by:         2147483647.0
Maximum amplitude:     0.681068
Minimum amplitude:    -0.459181
Midline amplitude:     0.110944
Mean    norm:          0.023196
Mean    amplitude:    -0.000018
RMS     amplitude:     0.045782
Maximum delta:         0.195640
Minimum delta:         0.000000
Mean    delta:         0.004389
RMS     delta:         0.009749
Rough   frequency:         1626
Volume adjustment:        1.468
```
The number of samples reported by soxi is the same as that of info.
```
❯ soxi  common_voice_en_100000.mp3

Input File     : 'common_voice_en_100000.mp3'
Channels       : 1
Sample Rate    : 48000
Precision      : 16-bit
Duration       : 00:00:01.94 = 93312 samples ~ 145.8 CDDA sectors
File Size      : 15.6k
Bit Rate       : 64.1k
Sample Encoding: MPEG audio (layer I, II or III)
```

**Comment by vincentqb** [comment] 2019-11-12 00:39
Since this is an upstream issue, I will close this. Please feel free to re-open.

**Closed by vincentqb** 2019-11-12 00:39 UTC

**Comment by noahbadoa** [comment] 2022-08-23 03:29
I also encountered torchaudio.info() being longer than the size of torchaudio.load() with version 0.11.1 on mp3s from the fma dataset. And in in version 0.12.1  torchaudio.info() returned 0.
[000002.zip](https://github.com/pytorch/audio/files/9399116/000002.zip)
.
