### ISSUE TITLE
"speed" effect does not work

### ISSUE THREAD

**Issue by lorenlugosch** [pytorch/audio#97] opened 2019-04-15 15:25 UTC
To reproduce: 
```
filename = "test.wav"

effect = torchaudio.sox_effects.SoxEffectsChain()
effect.set_input_file(filename)
effect.append_effect_to_chain("speed", 1.0)
x,sr = effect.sox_build_flow_effects()
x.shape

effect = torchaudio.sox_effects.SoxEffectsChain()
effect.set_input_file(filename)
effect.append_effect_to_chain("speed", 2.0)
x,sr = effect.sox_build_flow_effects()
x.shape
```

```x.shape``` will be the same for both.

The "tempo" effect does work, though. Weird, because these two effects have the same interface in SoX.

**Comment by engineerchuan** [comment] 2019-09-17 16:41
Hi Loren,

Can you try adding "rate" as well at the very end?

```
filename = "test.wav"
si, _ = torchaudio.info(filename )

effect = torchaudio.sox_effects.SoxEffectsChain()
effect.set_input_file(filename)
effect.append_effect_to_chain("speed", 1.0)
effect.append_effect_to_chain("rate", si.rate)
x,sr = effect.sox_build_flow_effects()
x.shape

effect = torchaudio.sox_effects.SoxEffectsChain()
effect.set_input_file(filename)
effect.append_effect_to_chain("speed", 2.0)
effect.append_effect_to_chain("rate", si.rate)
x,sr = effect.sox_build_flow_effects()
x.shape
```

I believe sox command line as a convenience layer that automatically adds the rate, but this is not in the C interface.  This should be a workaround.

**Comment by vincentqb** [comment] 2019-09-17 17:44
This resolves the issue on our end, and so I will close this issue. Please feel free to re-open if this does not fix it.

**Comment by lorenlugosch** [comment] 2019-10-03 22:58
Thanks @engineerchuan --- unfortunately now I get this error after `x,sr = effect.sox_build_flow_effects()`:

```
python: effects_i_dsp.c:189: update_fft_cache: Assertion `fft_len >= 0' failed.
Aborted (core dumped)
```

**Comment by vincentqb** [comment] 2019-10-04 15:28
On both the last release and master with python 3.7.4, this is successful
```
>>> effect = torchaudio.sox_effects.SoxEffectsChain()
>>> effect.set_input_file(filename)
>>> effect.append_effect_to_chain("speed", 1.0)
>>> x,sr = effect.sox_build_flow_effects()
>>> x.shape
torch.Size([2, 276858])
>>> 
>>> effect = torchaudio.sox_effects.SoxEffectsChain()
>>> effect.set_input_file(filename)
>>> effect.append_effect_to_chain("speed", 2.0)
>>> x,sr = effect.sox_build_flow_effects()
>>> x.shape
torch.Size([2, 276858])
```
However, not this:
```
>>> si, _ = torchaudio.info(filename )
>>> 
>>> effect = torchaudio.sox_effects.SoxEffectsChain()
>>> effect.set_input_file(filename)
>>> effect.append_effect_to_chain("speed", 1.0)
>>> effect.append_effect_to_chain("rate", si.rate)
>>> x,sr = effect.sox_build_flow_effects()
>>> x.shape
torch.Size([2, 276858])
>>> 
>>> effect = torchaudio.sox_effects.SoxEffectsChain()
>>> effect.set_input_file(filename)
>>> effect.append_effect_to_chain("speed", 2.0)
>>> effect.append_effect_to_chain("rate", si.rate)
>>> x,sr = effect.sox_build_flow_effects()
Assertion failed: (fft_len >= 0), function update_fft_cache, file effects_i_dsp.c, line 189.
```

**Comment by vincentqb** [comment] 2019-10-04 15:31
I cannot reproduce the original issue. If this continue, please feel free to re-open or create new [issue](https://github.com/pytorch/audio/issues/new?template=bug-report.md). In any case, please provide copy and paste the output from our [environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py). You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

**Comment by lorenlugosch** [comment] 2019-10-04 15:38
Hi @vincentqb, if you look at your first code block, `x.shape` is the same for both; it should be half in the second case. That was the original issue. The issue now is your second code block: using @engineerchuan 's workaround causes this error.

I'll try to use your script, though.

**Comment by vincentqb** [comment] 2019-10-04 15:39
Indeed, good point :)

**Comment by vincentqb** [comment] 2019-10-04 15:50
I at least don't get the segmentation fault when doubling the sample rate in the second part. This also reproduces the original code example.
```
>>> filename = "_static/img/steam-train-whistle-daniel_simon-converted-from-mp3.wav"
>>> si, _ = torchaudio.info(filename)
>>>
>>> effect = torchaudio.sox_effects.SoxEffectsChain()
>>> effect.set_input_file(filename)
>>> effect.append_effect_to_chain("speed", 1.0)
>>> effect.append_effect_to_chain("rate", si.rate)
>>> x,sr = effect.sox_build_flow_effects()
>>> x.shape
torch.Size([2, 276858])
>>> 
>>> effect = torchaudio.sox_effects.SoxEffectsChain()
>>> effect.set_input_file(filename)
>>> effect.append_effect_to_chain("speed", 2.0)
>>> effect.append_effect_to_chain("rate", si.rate*2)
>>> x,sr = effect.sox_build_flow_effects()
>>> x.shape
torch.Size([2, 276858])
```

**Comment by mthrok** [comment] 2020-11-03 21:32
The `SoxEffectChain` implementation is removed from torchaudio in #977 and the replacement implementation can handle this in the similar manner. (you still need to add `"rate"`, but it is documented clearly https://pytorch.org/audio/0.7/sox_effects.html#applying-effects-on-tensor

```python
import torchaudio

data, sr = torchaudio.sox_effects.apply_effects_file('test/torchaudio_unittest/assets/sinewave.wav', [['speed', '1.0'], ['rate', '16000']])
print(data.shape, sr)


data, sr = torchaudio.sox_effects.apply_effects_file('test/torchaudio_unittest/assets/sinewave.wav', [['speed', '2.0'], ['rate', '16000']])
print(data.shape, sr)
```

```
torch.Size([1, 64000]) 16000
torch.Size([1, 32000]) 16000
```

I am closing this issue, but @lorenlugosch if you are still experiencing the error with the latest torchaudio, let us know.

**Closed by mthrok** 2020-11-03 21:32 UTC
