### ISSUE TITLE
torchaudio.load() with mp3 file floods the console

### ISSUE THREAD

**Issue by maximecb** [pytorch/audio#357] opened 2019-11-26 15:47 UTC
Loading mp3 files with torchaudio.load() causes a lot of output in the console, eg:

```
mp3: MAD lost sync
mp3: recoverable MAD error
mp3: recoverable MAD error
mp3: recoverable MAD error
mp3: recoverable MAD error
mp3: recoverable MAD error
mp3: recoverable MAD error
mp3: recoverable MAD error
mp3: recoverable MAD error
mp3: recoverable MAD error
mp3: recoverable MAD error
mp3: recoverable MAD error
mp3: recoverable MAD error
mp3: recoverable MAD error
```

I'm on ubuntu 18.04 and using torchaudio 0.3.1. I would like to know if there is a known fix to quiet the console logging. If not, such a fix should probably be implemented.

**Comment by vincentqb** [comment] 2019-11-27 16:58
Can you provide steps to reproduce this, with a sample file (or say [this one](https://github.com/pytorch/audio/blob/master/test/assets/whitenoise_1min.mp3))?

**Comment by maximecb** [comment] 2019-11-27 17:26
Not able to reproduce it with the file you provided, but I can reproduce it with this mp3:
 http://www.mixotic.site/mixes/050_-_DJ_Kirill_Sergeew_-_Modern_Classiques_Vol_3/Mixotic_050_-_DJ_Kirill_Sergeew_-_Modern_Classiques_Vol_3_2006-09-25.mp3

When loading from an offset:

```
import torchaudio

# http://www.mixotic.site/mixes/050_-_DJ_Kirill_Sergeew_-_Modern_Classiques_Vol_3/Mixotic_050_-_DJ_Kirill_Sergeew_-_Modern_Classiques_Vol_3_2006-09-25.mp3
data = torchaudio.load('Mixotic_050_-_DJ_Kirill_Sergeew_-_Modern_Classiques_Vol_3_2006-09-25.mp3', num_frames=20000, offset=630000)
```

Running the script produces unwanted console output:
```
python3 test_load.py 
mp3: MAD lost sync
mp3: recoverable MAD error
```

This may not seem that bad, but if you're loading chunks of mp3 audio in a loop, it floods the console.

**Comment by vincentqb** [comment] 2019-11-27 22:52
Something is misread with this audio file using sox. In particular, it is not being read properly in between 63000 and 64000.

```
import torchaudio                                                                                                      
f = "Mixotic_050_-_DJ_K
irill_Sergeew_-_Modern_Classiques_Vol_3_2006-09-25.mp3"                                                                                           

t = torchaudio.load(f)
data = torchaudio.load(f, num_frames=20000, offset=630000)                                     
# mp3: MAD lost sync
# mp3: recoverable MAD error

(t[0][:,630000:(630000+20000)] - data[0]).abs().mean()                                                                                                          
# tensor(0.0023)

t[0][:,630000:(630000+20000)]                                                                                                                                           
# tensor([[-0.0726, -0.0734, -0.0684,  ...,  0.1730,  0.1710,  0.1692],
#         [-0.0867, -0.0886, -0.0867,  ...,  0.1738,  0.1713,  0.1696]])

data[0]                                                                                                                                                                 
# tensor([[0.0000, 0.0000, 0.0000,  ..., 0.1730, 0.1710, 0.1692],
#         [0.0000, 0.0000, 0.0000,  ..., 0.1738, 0.1713, 0.1696]])
```

We are discussing an option to change backend, see #355.

**Comment by mthrok** [comment] 2020-11-03 21:15
@maximecb 

Do you still experience the issue? With the latest torchaudio, I cannot reproduce the issue.
I will close the issue but feel free to reopen if you are still facing the issue.

**Closed by mthrok** 2020-11-03 21:15 UTC
