### ISSUE TITLE
Error thrown while reading FLAC files from file-like objects 

### ISSUE THREAD

**Issue by itz-vp** [pytorch/audio#2948] opened 2023-01-03 08:06 UTC
### Error thrown while reading flac file like objects

While loading an audio file from flac file path seems to be working fine, When reading the same file as a file like object throws an error

## minimal code to reproduce

```
import io
import torchaudio
import os

def get_binary_data(fpath: str) -> bytes:
    assert os.path.isfile(fpath)
    with open(fpath, "rb") as stream:
        binary_data = stream.read()
        return binary_data

torchaudio.set_audio_backend('sox_io')

audio, sample_rate = torchaudio.load("sample.flac")
print(len(audio.squeeze(0))/sample_rate)

audio = get_binary_data("sample.flac")
audio, sample_rate = torchaudio.load(io.BytesIO(audio))
print(len(audio.squeeze(0))/sample_rate)
```

## expected behaviour 

```
5.305854166666666
5.305854166666666
```

## output
```
5.305854166666666
formats: can't open input file `': FLAC ERROR whilst decoding metadata
Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?64e19f19-4197-4c6c-b456-82ccc0c176c4)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/home/local/ZOHOCORP/veera-pt4765/flac_issue/notebook.ipynb Cell 6' in <cell line: 2>()
      [1](vscode-notebook-cell:/home/local/ZOHOCORP/veera-pt4765/flac_issue/notebook.ipynb#ch0000004?line=0) audio = get_binary_data("sample.flac")
----> [2](vscode-notebook-cell:/home/local/ZOHOCORP/veera-pt4765/flac_issue/notebook.ipynb#ch0000004?line=1) audio, sample_rate = torchaudio.load(io.BytesIO(audio))
      [3](vscode-notebook-cell:/home/local/ZOHOCORP/veera-pt4765/flac_issue/notebook.ipynb#ch0000004?line=2) len(audio.squeeze(0))/sample_rate

File ~/anaconda3/envs/zspeech/lib/python3.8/site-packages/torchaudio/backend/sox_io_backend.py:220, in load(filepath, frame_offset, num_frames, normalize, channels_first, format)
    218         if ret is not None:
    219             return ret
--> 220         return _fallback_load_fileobj(filepath, frame_offset, num_frames, normalize, channels_first, format)
    221     filepath = os.fspath(filepath)
    222 ret = torch.ops.torchaudio.sox_io_load_audio_file(
    223     filepath, frame_offset, num_frames, normalize, channels_first, format
    224 )

File ~/anaconda3/envs/zspeech/lib/python3.8/site-packages/torchaudio/io/_compat.py:114, in load_audio_fileobj(src, frame_offset, num_frames, convert, channels_first, format)
    106 def load_audio_fileobj(
    107     src: str,
    108     frame_offset: int = 0,
   (...)
    112     format: Optional[str] = None,
    113 ) -> Tuple[torch.Tensor, int]:
--> 114     s = torchaudio._torchaudio_ffmpeg.StreamReaderFileObj(src, format, None, 4096)
    115     return _load_audio(s, frame_offset, num_frames, convert, channels_first)
...
frame #60: PyVectorcall_Call + 0x78 (0x4e8d08 in /home/local/ZOHOCORP/veera-pt4765/anaconda3/envs/zspeech/bin/python)
frame #61: _PyEval_EvalFrameDefault + 0x5bd8 (0x4ccbb8 in /home/local/ZOHOCORP/veera-pt4765/anaconda3/envs/zspeech/bin/python)
frame #62: _PyFunction_Vectorcall + 0x106 (0x4da136 in /home/local/ZOHOCORP/veera-pt4765/anaconda3/envs/zspeech/bin/python)
frame #63: _PyEval_EvalFrameDefault + 0xa3e (0x4c7a1e in /home/local/ZOHOCORP/veera-pt4765/anaconda3/envs/zspeech/bin/python)
```
## Alternatives which worked
```
torchaudio.set_audio_backend('soundfile')

audio = get_binary_data("sample.flac")
audio, sample_rate = torchaudio.load(io.BytesIO(audio))
print(len(audio.squeeze(0))/sample_rate)
```

## Resources to reproduce
[notebook](https://workdrive.zohoexternal.com/external/24d6942e01338fb4e22d31adae8f88d12ba41078d27059225031c169cf060eb5)
[raw audio used in notebook](https://workdrive.zohoexternal.com/external/f1aadc9d4d9b6a33b82fe10d94ee795fb68eb31126e3f969ed386df260be210f)

[flac audio with issue](https://workdrive.zohoexternal.com/external/d181a1a6eec9873a56602f8aa4ffe6cd36df186fce5a5d578e8880f23ad2da41)

## Notes
- The flac file then converted to `wav` and loaded the same as file like object. Worked 

### Versions

```
Collecting environment information...
PyTorch version: 1.13.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.15 (default, Nov 24 2022, 15:19:38)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.14.0-1054-oem-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.961
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.4
[pip3] pytorch-lightning==1.5.10
[pip3] torch==1.13.0
[pip3] torch-poly-lr-decay==0.0.1
[pip3] torchaudio==0.13.0
[pip3] torchmetrics==0.10.2
[conda] numpy                     1.23.4                   pypi_0    pypi
[conda] pytorch-lightning         1.5.10                   pypi_0    pypi
[conda] torch                     1.13.0                   pypi_0    pypi
[conda] torch-poly-lr-decay       0.0.1                    pypi_0    pypi
[conda] torchaudio                0.13.0                   pypi_0    pypi
[conda] torchmetrics              0.10.2                   pypi_0    pypi
```

**Comment by mthrok** [comment] 2023-01-10 13:49
This issue is likely duplicate of https://github.com/pytorch/audio/issues/2356, and this is another limitation of libsox.

Can you try increasing the memory buffer size? 
https://pytorch.org/audio/stable/generated/torchaudio.utils.sox_utils.html#set-buffer-size

**Comment by itz-vp** [comment] 2023-01-18 08:14
Thank @mthrok . changing buffer size from 16000 to 16020 works, May I know what was the limitation in libsox ?

**Comment by mthrok** [comment] 2023-01-23 16:49
> Thanks @mthrok . changing buffer size from 16000 to 16020 works for 1 sample audio and for other sample audio 16500 buffer size works, May I know what was the limitation in libsox ? do you have any idea how much buffer size should be ideal to load audios in 48k samplerate ? Thanks in advance.

libsox does not natively support streaming decoding. Its API/interface is for decoding media which is fully stored in memory. We employed some hack to update the underlying buffer in streaming fashion. However, if the libsox implementation reach the end of this underlying buffer, it assumes that the file ends there which leads to the error you encountered.

The ideal size of buffer depends on format and header data, I think but not entirely sure. I think 16500 should work for FLAC, but some formats like OPUS do not have upper limit of header size on spec, so it could be insufficient (though in practice, it should be sufficient)

**Comment by mthrok** [comment] 2023-01-23 16:50
FYI: For the reason above we are migrating the file-like object support to FFmpeg-based implementation.

**Closed by mthrok** 2023-01-23 16:49 UTC
Labels: triaged
