### ISSUE TITLE
unable to load torchaudio after installing torchaudio==0.12.0

### ISSUE THREAD

**Issue by yilinw92** [pytorch/audio#2731] opened 2022-10-03 03:48 UTC
### 🐛 Describe the bug

**Problem description:**
I am trying to setting up environment on Nvidia Jetson Xavier NX, I have successfully make cuda, pytorch working since torch.cuda.is_available() is True. The problem occurs when I am trying to import torchaudio which I have already successfully installed and I think it is with the correct version 0.12.0 for torch 1.12.0

**Device:** 
Nvidia Jetson Xavier NX
Jetpack 5.0.2

**package version**
yilinw@ubuntu:~$ pip list | grep torch
pytorch-lightning       1.7.7                  
torch                   1.12.0a0+84d1cb9.nv22.4
torchaudio              0.12.1                 
torchmetrics            0.9.3                  
torchvision             0.13.1   

**Unable to load torchaudio**
```
yilinw@ubuntu:~$ python3
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torchaudio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yilinw/.local/lib/python3.8/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/home/yilinw/.local/lib/python3.8/site-packages/torchaudio/_extension.py", line 103, in <module>
    _init_extension()
  File "/home/yilinw/.local/lib/python3.8/site-packages/torchaudio/_extension.py", line 88, in _init_extension
    _load_lib("libtorchaudio")
  File "/home/yilinw/.local/lib/python3.8/site-packages/torchaudio/_extension.py", line 51, in _load_lib
    torch.ops.load_library(path)
  File "/home/yilinw/.local/lib/python3.8/site-packages/torch/_ops.py", line 244, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/yilinw/.local/lib/python3.8/site-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZNK5torch8autograd4Node4nameEv
```

Am I having trouble with incompatible issue between pytorch and torchaudio?
Thank you for your help.

### Versions

python /home/yilinw/Projects/ASC/demo/collect_env.py
Collecting environment information...
Traceback (most recent call last):
  File "/home/yilinw/Projects/ASC/demo/collect_env.py", line 492, in <module>
    main()
  File "/home/yilinw/Projects/ASC/demo/collect_env.py", line 475, in main
    output = get_pretty_env_info()
  File "/home/yilinw/Projects/ASC/demo/collect_env.py", line 470, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "/home/yilinw/Projects/ASC/demo/collect_env.py", line 319, in get_env_info
    pip_version, pip_list_output = get_pip_packages(run_lambda)
  File "/home/yilinw/Projects/ASC/demo/collect_env.py", line 301, in get_pip_packages
    out = run_with_pip(sys.executable + ' -mpip')
  File "/home/yilinw/Projects/ASC/demo/collect_env.py", line 289, in run_with_pip
    for line in out.splitlines()
AttributeError: 'NoneType' object has no attribute 'splitlines'

**Comment by mthrok** [comment] 2022-10-03 06:37
Hi - We do not provide pre-built binary that works with Jetson out-of-box. Torchaudio's pre-built binary only works with official PyTorch binary distribution. So I think you need to build torchaudio from source.

**Comment by yilinw92** [comment] 2022-10-07 03:09
I have flashed my sd card, and it seems like I am able to collect the results from collect_env file.
Collecting environment information...
PyTorch version: 1.12.0a0+2c916ef.nv22.3
Is debug build: False
CUDA used to build PyTorch: 11.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (aarch64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.10.104-tegra-aarch64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.4.239
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/aarch64-linux-gnu/libcudnn.so.8.4.1
/usr/lib/aarch64-linux-gnu/libcudnn_adv_infer.so.8.4.1
/usr/lib/aarch64-linux-gnu/libcudnn_adv_train.so.8.4.1
/usr/lib/aarch64-linux-gnu/libcudnn_cnn_infer.so.8.4.1
/usr/lib/aarch64-linux-gnu/libcudnn_cnn_train.so.8.4.1
/usr/lib/aarch64-linux-gnu/libcudnn_ops_infer.so.8.4.1
/usr/lib/aarch64-linux-gnu/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

Versions of relevant libraries:
[pip3] numpy==1.17.4
[pip3] torch==1.12.0a0+2c916ef.nv22.3
[pip3] torchaudio==0.12.0
[pip3] torchvision==0.13.0
[conda] Could not collect


To make reproducing this problem easier, you can flash jetpack 5.0.2 rev1 by using Nvidia SDK manager. 
download wheels 
for pytorch 1.12.0:  https://developer.download.nvidia.com/compute/redist/jp/v50/pytorch/torch-1.12.0a0+2c916ef.nv22.3-cp38-cp38-linux_aarch64.whl
for torchaudio 0.12.0: https://download.pytorch.org/whl/torchaudio-0.12.0-cp38-cp38-manylinux2014_aarch64.whl
for torchvision 0.13.0: https://download.pytorch.org/whl/torchvision-0.13.0-cp38-cp38-manylinux2014_aarch64.whl

After I type python3
>>> import torch
>>> torch.cuda.is_available()
True

>>> import torchaudio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yilinw/astrtd/lib/python3.8/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/home/yilinw/astrtd/lib/python3.8/site-packages/torchaudio/_extension.py", line 103, in <module>
    _init_extension()
  File "/home/yilinw/astrtd/lib/python3.8/site-packages/torchaudio/_extension.py", line 88, in _init_extension
    _load_lib("libtorchaudio")
  File "/home/yilinw/astrtd/lib/python3.8/site-packages/torchaudio/_extension.py", line 51, in _load_lib
    torch.ops.load_library(path)
  File "/home/yilinw/astrtd/lib/python3.8/site-packages/torch/_ops.py", line 244, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/yilinw/astrtd/lib/python3.8/site-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZNK5torch8autograd4Node4nameEv


>>> import torchvision
/home/yilinw/astrtd/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")

**Comment by mthrok** [comment] 2023-08-01 01:54
Closing as the problem is mixing different distributions of pytorch and torchaudio/torchvision, which is not something we can fix.

**Closed by mthrok** 2023-08-01 01:54 UTC
