### ISSUE TITLE
INSTALLATION ON COLAB

### ISSUE THREAD

**Issue by jafarOlamide** [pytorch/audio#356] opened 2019-11-26 07:58 UTC
Hello, I am trying to install torchaudio on colab and I have the following errors,  what could have gone wrong 

```
ERROR: Failed building wheel for torchaudio
  Running setup.py clean for torchaudio
Failed to build torchaudio
Installing collected packages: torchaudio
    Running setup.py install for torchaudio ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-a6qs5kpn/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-a6qs5kpn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-gu058e03/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
```

I used the following code: 
`!pip install git+git://github.com/pytorch/audio`
after installing all dependencies on colab. 
Thanks

**Comment by akalmbach** [comment] 2019-12-04 05:39
FWIW if you can live with what's in pypi `!pip install torchaudio` seems to work. If you need something from master I can confirm I see this error as well.

**Comment by vincentqb** [comment] 2019-12-14 01:05
The command `pip install git+git://github.com/pytorch/audio` fails on mac. This is not currently supported. 

Since I am able to install on colab using `!pip install torchaudio`, I will close this issue. Please feel free to re-open if you do need master instead of the latest release.

**Closed by vincentqb** 2019-12-14 01:05 UTC
