### ISSUE TITLE
torchaudio with RTX 3090 

### ISSUE THREAD

**Issue by amiguelartiaga** [pytorch/audio#1047] opened 2020-11-18 19:55 UTC
I have followed the nightly build install instructions recommended for the new GPU: RTX 3090, shown in:

[https://github.com/PyTorchLightning/pytorch-lightning/issues/4587](https://github.com/PyTorchLightning/pytorch-lightning/issues/4587)
[https://github.com/pytorch/pytorch/issues/45028](https://github.com/pytorch/pytorch/issues/45028)

 `pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu110/torch_nightly.html`

(I have also tried)
`conda install pytorch torchvision cudatoolkit=11 -c pytorch-nightly`

But, once pytorch is installed and it works with the new gpu,  I have not been able to install torchaudio. How can I install torchaudio + pytorch to work with RTX 3090 ?

Thanks in advance,

**Comment by vincentqb** [comment] 2020-11-18 20:05
Thanks for opening the issue! Can you provide the output of each command and how the installation is failing? In particular, can you provide the error message when you try to run the following?
```
!pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu110/torch_nightly.html
```
Similarly for conda.

**Comment by amiguelartiaga** [comment] 2020-11-18 20:52
Thank you,
I have tried as you suggest:
`pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu110/torch_nightly.html
Looking in links: https://download.pytorch.org/whl/nightly/cu110/torch_nightly.html
Collecting torch
  Using cached https://download.pytorch.org/whl/nightly/cu110/torch-1.8.0.dev20201118%2Bcu110-cp38-cp38-linux_x86_64.whl (1210.5 MB)
Collecting torchvision
  Using cached https://download.pytorch.org/whl/nightly/cu110/torchvision-0.9.0.dev20201118%2Bcu110-cp38-cp38-linux_x86_64.whl (13.2 MB)
Collecting torchaudio
  Using cached https://download.pytorch.org/whl/nightly/torchaudio-0.8.0.dev20201118-cp38-cp38-linux_x86_64.whl (7.5 MB)
Requirement already satisfied: numpy in ./miniconda3/lib/python3.8/site-packages (from torch) (1.19.4)
Collecting typing-extensions
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Requirement already satisfied: pillow>=4.1.1 in ./miniconda3/lib/python3.8/site-packages (from torchvision) (8.0.1)
ERROR: torchaudio 0.8.0.dev20201118 has requirement torch==1.8.0.dev20201118+cpu, but you'll have torch 1.8.0.dev20201118+cu110 which is incompatible.
Installing collected packages: typing-extensions, torch, torchvision, torchaudio
Successfully installed torch-1.8.0.dev20201118+cu110 torchaudio-0.8.0.dev20201118 torchvision-0.9.0.dev20201118+cu110 typing-extensions-3.7.4.3`

Despite the error message I have tried a small sample and seems to work. This is the final list of packages. I don't know if torchaudio should also be cu110, will it perform optimally like this ?
`conda list | grep torch
torch                     1.8.0.dev20201118+cu110          pypi_0    pypi
torchaudio                0.8.0.dev20201118          pypi_0    pypi
torchvision               0.9.0.dev20201118+cu110          pypi_0    pypi
`

With conda is not working at all (I cut the output because it is too long):
`conda install pytorch torchvision torchaudio cudatoolkit=11 -c pytorch-nightly
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                    -  

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - conda-package-handling -> python[version='>=3.5,<3.6.0a0']
  - conda[version='>=4.8.3'] -> python[version='>=3.5,<3.6.0a0|>=3.9,<3.10.0a0']
  - cryptography -> python[version='<=3.3']
  - pyopenssl -> python[version='>=3.9,<3.10.0a0']
  - torchaudio -> python[version='>=3.9,<3.10.0a0']
  - torchvision -> python[version='>=3.9,<3.10.0a0']
  - tqdm -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']
  - urllib3 -> python[version='<=3.3|>=3.9,<3.10.0a0']
  - wheel -> python[version='>=3.9,<3.10.0a0']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package sqlite conflicts for:
torchaudio -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.24.0,<4.0a0|>=3.25.2,<4.0a0|>=3.26.0,<4.0a0|>=3.29.0,<4.0a0|>=3.30.1,<4.0a0|>=3.31.1,<4.0a0|>=3.33.0,<4.0a0|>=3.27.2,<4.0a0|>=3.25.3,<4.0a0|>=3.32.3,<4.0a0|>=3.30.0,<4.0a0']
`

Thanks,

**Comment by vincentqb** [comment] 2020-11-19 15:21
thanks for adding information @amiguelartiaga!

@seemethere -- are the packages for cuda 11 also available through some other mean?

**Comment by tyoc213** [comment] 2021-03-23 08:10
I think not in pip or conda, but taking above command and changing to latest driver worked (which was a pain for me and Ubuntu latest driver)

`!pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu112/torch_nightly.html`

![image](https://user-images.githubusercontent.com/506234/112112323-ffdee200-8b7a-11eb-9159-2f2ab16a8920.png)

But don't know why it downloaded 1.9 nightly and later 1.8

![image](https://user-images.githubusercontent.com/506234/112112931-c490e300-8b7b-11eb-8f3d-7f22533753c6.png)

![image](https://user-images.githubusercontent.com/506234/112112959-ce1a4b00-8b7b-11eb-9c1a-4e4d699b7b59.png)
![image](https://user-images.githubusercontent.com/506234/112113114-028e0700-8b7c-11eb-8b5d-357816c983e7.png)

mmmmmm so

```
$ python
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.8.0'

```

I uninstalled then asked only for `torch` and `torchaudio`... still got 1.8 and the `anylinux` version which I think is not the right one for cuda 11.2.

It installs 1.9 cuda 11.2 (https://download.pytorch.org/whl/nightly/cu112/torch-1.9.0.dev20210217%2Bcu112-cp38-cp38-linux_x86_64.whl) if I ask only for torch like `pip install --pre torch  -f https://download.pytorch.org/whl/nightly/cu112/torch_nightly.html`

You know how to install torch audio and vision for 1.9 cuda 11.2?

```
>>> import torch
>>> torch.__version__
'1.9.0.dev20210217+cu112'
```

**Comment by mthrok** [comment] 2022-07-29 23:28
closing as it's been a while since the issue is filed and we had multiple releases since then. Please try the latest one and file a new issue if it does not work.

**Closed by mthrok** 2022-07-29 23:28 UTC
